---
motorcade_timezone: "UTC"

motorcade_nginx_domains: []

motorcade_nginx_tls_cert_dir: /etc/pki/tls/motorcade

keycloak_db_mode: rds
keycloak_db_port: 5432
keycloak_db_name: keycloak
keycloak_db_user: keycloak
keycloak_hostname: ""

podman_bin_candidates:
  - /usr/bin/podman

motorcade_podman_api_enabled: false
