---
motorcade_base_dir: /srv/motorcade
motorcade_vol_dir: "{{ motorcade_base_dir }}/volumes"
motorcade_conf_dir: "{{ motorcade_base_dir }}/config"

nginx_image: docker.io/library/nginx:latest
keycloak_image: quay.io/keycloak/keycloak:26.5.3

nginx_http_port: 80
nginx_https_port: 443
nginx_use_quadlet: true

motorcade_nginx_domains:
  - motorcade.vip
  - sso.motorcade.vip
  - admin.motorcade.vip
  - mcp.motorcade.vip
motorcade_nginx_static_root: "/var/www/motorcade-site"

keycloak_bind_host: 127.0.0.1
keycloak_http_port: 8080
keycloak_use_quadlet: true

# Keycloak RDS / Secrets Manager wiring for prod
keycloak_db_host: "motorcade-prod-db-01.cdcs4864s0l0.us-east-2.rds.amazonaws.com"
keycloak_db_secret_arn: "arn:aws:secretsmanager:us-east-2:703671899211:secret:rds!db-30cc9705-6861-4d27-bdd3-a2d3817739b8-Gu1GDf"

# Keycloak admin credentials for deployment
keycloak_admin_user: "admin"
keycloak_admin_password: "CHANGE_THIS_TO_A_STRONG_PASSWORD"

# Keycloak admin creds live in Secrets Manager (JSON: {"username":"...","password":"..."})
keycloak_admin_secret_arn: "arn:aws:secretsmanager:us-east-2:703671899211:secret:motorcade/prod/keycloak-admin-GO6mCg"
