---
# Non-sensitive reference (ARN/Name only). Values stay in AWS Secrets Manager.
rds_admin_secret_id: "arn:aws:secretsmanager:us-east-2:703671899211:secret:rds!db-30cc9705-6861-4d27-bdd3-a2d3817739b8-Gu1GDf"
