$ANSIBLE_VAULT;1.1;AES256
62343738306135633431633939653836373737316263643333373131333438333538313630663439
3364343038636561313739326139356535626161653164350a653164663562353739613231313664
32613933346231323536336661663535663537616163326261343430313162653634393537323136
3631633530366137360a373165373735366663336435393636613263393732616566326130393163
65383938643833666631376363333361663336653661393063393535313939353134306662383738
65366262306332626566373732643766316430633662313363343438376632336433643934356162
37313336616366316334336539396561336536623163323338353331353934323366633035396631
31653965396165613766643235663063393361343331343133626562333234373264316231353962
39313461366432613239383538353131633431666138306439386432623561386333
